from pathlib import Path
import re

root = Path(r'd:\users\Anonymous\Documents\C Sharp\VirtuoPhoneGamePadWin')
files = list(root.rglob('Models/**/*.cs'))
print('Processing', len(files), 'files')
for p in files:
    text = p.read_text(encoding='utf-8')
    original = text
    # Replace Java-style collection and loop syntax
    text = re.sub(r'\bforeach \(int i = 1; i < lineList\.Length; i\+\+\) \{', 'for (int i = 1; i < lineList.Length; i++)\n    {', text)
    text = re.sub(r'for \(([^\s:]+) ([^:]+): ([^\)]+)\)', r'foreach (\1 \2 in \3)', text)
    text = text.replace('random.nextInt(', 'random.Next(')
    text = text.replace('multiSampleList.length', 'multiSampleList.Length')
    text = text.replace('lineList.length', 'lineList.Length')
    text = text.replace('stringBuilder.append(', 'stringBuilder.Append(')
    text = text.replace('.append(', '.Append(')
    text = text.replace('lineList.length', 'lineList.Length')
    text = text.replace('.size()', '.Count')
    text = text.replace('.add(', '.Add(')
    text = text.replace('.remove(', '.Remove(')
    text = text.replace('.containsKey(', '.ContainsKey(')
    text = text.replace('.keySet()', '.Keys')
    text = text.replace('.clear()', '.Clear()')
    text = text.replace('Math.pow(', 'Math.Pow(')
    text = text.replace('Math.abs(', 'Math.Abs(')
    text = text.replace('new TreeMap<Integer, Integer>()', 'new Dictionary<int, int>()')
    text = text.replace('TreeMap<Integer, Integer>', 'Dictionary<int, int>')
    text = re.sub(r'\bsynchronized\s*\(', 'lock(', text)
    text = text.replace('random.nextInt', 'random.Next')
    text = re.sub(r'\bnew Vector<([^>]+)>\(\)', r'new List<\1>()', text)
    text = re.sub(r'\bnew ArrayList<([^>]+)>\(\)', r'new List<\1>()', text)
    text = re.sub(r'\bnew HashSet<([^>]+)>\(\)', r'new HashSet<\1>()', text)
    text = text.replace('sampleList.add(sample);', 'sampleList.Add(sample);')
    text = text.replace('noteList.add(new Note', 'noteList.Add(new Note')
    text = text.replace('chordList.add(new Chord', 'chordList.Add(new Chord')
    text = text.replace('chordList.add(chord);', 'chordList.Add(chord);')
    text = text.replace('chordList.remove(chordList.indexOf(chord));', 'chordList.Remove(chord);')
    text = text.replace('chordList.indexOf(oldChord)', 'chordList.IndexOf(oldChord)')
    text = re.sub(r'public IEnumerator<([^>]+)> iterator\(\)', r'public IEnumerator<\1> GetEnumerator()', text)
    text = re.sub(r'public IEnumerator<([^>]+)> GetEnumerator\(\)\s*\{\s*return ([^;]+);\s*\}', r'public IEnumerator<\1> GetEnumerator()\n    {\n        return \2;\n    }', text)
    text = re.sub(r'public string toString\(\)', 'public override string ToString()', text)
    text = re.sub(r'public int size\(\)', 'public int Size()', text)
    text = re.sub(r'public void addNote\(Note note\)', 'public void AddNote(Note note)', text)
    text = re.sub(r'public int lastPitch\(\)', 'public int LastPitch()', text)
    text = re.sub(r'public bool containsExact\(Note note\)', 'public bool ContainsExact(Note note)', text)
    text = re.sub(r'public void setName\(string name\)', 'public void SetName(string name)', text)
    text = re.sub(r'public string getName\(\)', 'public string GetName()', text)
    text = re.sub(r'public void setChord\(int index, Chord chord\)', 'public void SetChord(int index, Chord chord)', text)
    text = re.sub(r'public string serialize\(\)', 'public string Serialize()', text)
    text = re.sub(r'public int getChordTypeId\(\)', 'public int GetChordTypeId()', text)
    text = re.sub(r'public int getNoteType\(\)', 'public int GetNoteType()', text)
    text = re.sub(r'public int getPitch\(\)', 'public int GetPitch()', text)
    text = re.sub(r'public void setPitch\(int pitch\)', 'public void SetPitch(int pitch)', text)
    text = re.sub(r'public int getOriginalPitch\(\)', 'public int GetOriginalPitch()', text)
    text = re.sub(r'public float getPitchMultiplicator\(', 'public float GetPitchMultiplicator(', text)
    text = re.sub(r'public int getResourceId\(\)', 'public int GetResourceId()', text)
    text = re.sub(r'public int getSoundId\(\)', 'public int GetSoundId()', text)
    text = re.sub(r'public float getVolume\(\)', 'public float GetVolume()', text)
    text = re.sub(r'public int getStreamIdFromString\(int stringId\)', 'public int GetStreamIdFromString(int stringId)', text)
    text = re.sub(r'public void remember\(int stringId, int streamId\)', 'public void Remember(int stringId, int streamId)', text)
    text = re.sub(r'public void remove\(Note mostExtremeNote\)', 'public void Remove(Note mostExtremeNote)', text)

    # fix control flow indent in single-line block cases
    text = re.sub(r'\n(\s{8}if \([^\)]+\))\n\s{8}([^\s\n].*)', r'\n\1\n        \2', text)
    text = re.sub(r'\n(\s{8}while \([^\)]+\))\n\s{8}([^\s\n].*)', r'\n\1\n        \2', text)

    if text != original:
        p.write_text(text, encoding='utf-8')
        print('Patched', p)
print('Done')
