// <auto-generated/> Resource id table generated from res/raw/*.ogg and R.Raw.* code references.
// Regenerate when samples change (see CLAUDE.md). Ids map to res/raw/<name>.ogg when the file exists.
#nullable enable
using System.Collections.Generic;

namespace VirtuoPhone.Models;

public static class R
{
    public static class Raw
    {
        public const int bagpipesa0 = 1;
        public const int bagpipesa2 = 2;
        public const int bagpipesb1 = 3;
        public const int bagpipesd1 = 4;
        public const int bagpipesdroneloopa = 5;
        public const int bagpipese0 = 6;
        public const int bagpipese2 = 7;
        public const int bagpipesg1 = 8;
        public const int guimb1 = 9;
        public const int guimb10 = 10;
        public const int guimb11 = 11;
        public const int guimb12 = 12;
        public const int guimb14 = 13;
        public const int guimb15 = 14;
        public const int guimb17 = 15;
        public const int guimb2 = 16;
        public const int guimb20 = 17;
        public const int guimb23 = 18;
        public const int guimb25 = 19;
        public const int guimb26 = 20;
        public const int guimb3 = 21;
        public const int guimb30 = 22;
        public const int guimb31 = 23;
        public const int guimb32 = 24;
        public const int guimb34 = 25;
        public const int guimb35 = 26;
        public const int guimb36 = 27;
        public const int guimb5 = 28;
        public const int guimb6 = 29;
        public const int guimb7 = 30;
        public const int guimb8 = 31;
        public const int guimb9 = 32;
        public const int guitara2 = 33;
        public const int guitarb3 = 34;
        public const int guitard3 = 35;
        public const int guitare2 = 36;
        public const int guitare4 = 37;
        public const int guitarg3 = 38;
        public const int harpa0 = 39;
        public const int harpa2 = 40;
        public const int harpb1 = 41;
        public const int harpb3 = 42;
        public const int harpd1 = 43;
        public const int harpd3 = 44;
        public const int harpe0 = 45;
        public const int harpe2 = 46;
        public const int harpe4 = 47;
        public const int harpg1 = 48;
        public const int harpg3 = 49;
        public const int harpsichorda0 = 50;
        public const int harpsichorda2 = 51;
        public const int harpsichordb1 = 52;
        public const int harpsichordb3 = 53;
        public const int harpsichordd1 = 54;
        public const int harpsichordd3 = 55;
        public const int harpsichorde2 = 56;
        public const int harpsichorde4 = 57;
        public const int harpsichordf0 = 58;
        public const int harpsichordg1 = 59;
        public const int harpsichordg3 = 60;
        public const int pianoa0 = 61;
        public const int pianoa2 = 62;
        public const int pianob1 = 63;
        public const int pianob3 = 64;
        public const int pianod1 = 65;
        public const int pianod3 = 66;
        public const int pianoe0 = 67;
        public const int pianoe2 = 68;
        public const int pianoe4 = 69;
        public const int pianog1 = 70;
        public const int pianog3 = 71;
        public const int sitardronec = 72;
        public const int sitardroneshortc = 73;
        public const int sitarea2 = 74;
        public const int sitarea4 = 75;
        public const int sitareb3 = 76;
        public const int sitareb5 = 77;
        public const int sitarecsharp6 = 78;
        public const int sitared3 = 79;
        public const int sitared5 = 80;
        public const int sitaredroneshortcsharp = 81;
        public const int sitaree2 = 82;
        public const int sitaree4 = 83;
        public const int sitaree6 = 84;
        public const int sitareg3 = 85;
        public const int sitareg5 = 86;
        public const int syntha0 = 87;
        public const int syntha2 = 88;
        public const int synthb1 = 89;
        public const int synthb3 = 90;
        public const int synthd1 = 91;
        public const int synthd3 = 92;
        public const int synthe0 = 93;
        public const int synthe2 = 94;
        public const int synthe4 = 95;
        public const int synthg1 = 96;
        public const int synthg3 = 97;
        public const int tampuracsharp = 98;
        public const int tampuracsharpshort = 99;
        public const int violina0 = 100;
        public const int violina2 = 101;
        public const int violinb1 = 102;
        public const int violinb3 = 103;
        public const int violind1 = 104;
        public const int violind3 = 105;
        public const int violine0 = 106;
        public const int violine2 = 107;
        public const int violine4 = 108;
        public const int violing1 = 109;
        public const int violing3 = 110;
    }

    // Resource id -> file name under res/raw (only ids whose .ogg is bundled).
    private static readonly Dictionary<int, string> fileById = new()
    {
        { 1, "bagpipesa0.ogg" },
        { 2, "bagpipesa2.ogg" },
        { 3, "bagpipesb1.ogg" },
        { 4, "bagpipesd1.ogg" },
        { 5, "bagpipesdroneloopa.ogg" },
        { 6, "bagpipese0.ogg" },
        { 7, "bagpipese2.ogg" },
        { 8, "bagpipesg1.ogg" },
        { 9, "guimb1.ogg" },
        { 10, "guimb10.ogg" },
        { 11, "guimb11.ogg" },
        { 12, "guimb12.ogg" },
        { 13, "guimb14.ogg" },
        { 14, "guimb15.ogg" },
        { 15, "guimb17.ogg" },
        { 16, "guimb2.ogg" },
        { 17, "guimb20.ogg" },
        { 18, "guimb23.ogg" },
        { 19, "guimb25.ogg" },
        { 20, "guimb26.ogg" },
        { 21, "guimb3.ogg" },
        { 22, "guimb30.ogg" },
        { 23, "guimb31.ogg" },
        { 24, "guimb32.ogg" },
        { 25, "guimb34.ogg" },
        { 26, "guimb35.ogg" },
        { 27, "guimb36.ogg" },
        { 28, "guimb5.ogg" },
        { 29, "guimb6.ogg" },
        { 30, "guimb7.ogg" },
        { 31, "guimb8.ogg" },
        { 32, "guimb9.ogg" },
        { 33, "guitara2.ogg" },
        { 34, "guitarb3.ogg" },
        { 35, "guitard3.ogg" },
        { 36, "guitare2.ogg" },
        { 37, "guitare4.ogg" },
        { 38, "guitarg3.ogg" },
        { 39, "harpa0.ogg" },
        { 40, "harpa2.ogg" },
        { 41, "harpb1.ogg" },
        { 42, "harpb3.ogg" },
        { 43, "harpd1.ogg" },
        { 44, "harpd3.ogg" },
        { 45, "harpe0.ogg" },
        { 46, "harpe2.ogg" },
        { 47, "harpe4.ogg" },
        { 48, "harpg1.ogg" },
        { 49, "harpg3.ogg" },
        { 50, "harpsichorda0.ogg" },
        { 51, "harpsichorda2.ogg" },
        { 52, "harpsichordb1.ogg" },
        { 53, "harpsichordb3.ogg" },
        { 54, "harpsichordd1.ogg" },
        { 55, "harpsichordd3.ogg" },
        { 56, "harpsichorde2.ogg" },
        { 57, "harpsichorde4.ogg" },
        { 58, "harpsichordf0.ogg" },
        { 59, "harpsichordg1.ogg" },
        { 60, "harpsichordg3.ogg" },
        { 61, "pianoa0.ogg" },
        { 62, "pianoa2.ogg" },
        { 63, "pianob1.ogg" },
        { 64, "pianob3.ogg" },
        { 65, "pianod1.ogg" },
        { 66, "pianod3.ogg" },
        { 67, "pianoe0.ogg" },
        { 68, "pianoe2.ogg" },
        { 69, "pianoe4.ogg" },
        { 70, "pianog1.ogg" },
        { 71, "pianog3.ogg" },
        { 72, "sitardronec.ogg" },
        { 73, "sitardroneshortc.ogg" },
        { 74, "sitarea2.ogg" },
        { 75, "sitarea4.ogg" },
        { 76, "sitareb3.ogg" },
        { 77, "sitareb5.ogg" },
        { 78, "sitarecsharp6.ogg" },
        { 79, "sitared3.ogg" },
        { 80, "sitared5.ogg" },
        { 81, "sitaredroneshortcsharp.ogg" },
        { 82, "sitaree2.ogg" },
        { 83, "sitaree4.ogg" },
        { 84, "sitaree6.ogg" },
        { 85, "sitareg3.ogg" },
        { 86, "sitareg5.ogg" },
        { 87, "syntha0.ogg" },
        { 88, "syntha2.ogg" },
        { 89, "synthb1.ogg" },
        { 90, "synthb3.ogg" },
        { 91, "synthd1.ogg" },
        { 92, "synthd3.ogg" },
        { 93, "synthe0.ogg" },
        { 94, "synthe2.ogg" },
        { 95, "synthe4.ogg" },
        { 96, "synthg1.ogg" },
        { 97, "synthg3.ogg" },
        { 98, "tampuracsharp.ogg" },
        { 99, "tampuracsharpshort.ogg" },
        { 100, "violina0.ogg" },
        { 101, "violina2.ogg" },
        { 102, "violinb1.ogg" },
        { 103, "violinb3.ogg" },
        { 104, "violind1.ogg" },
        { 105, "violind3.ogg" },
        { 106, "violine0.ogg" },
        { 107, "violine2.ogg" },
        { 108, "violine4.ogg" },
        { 109, "violing1.ogg" },
        { 110, "violing3.ogg" },
    };

    /// <summary>File name under res/raw for a resource id, or null when no sample is bundled.</summary>
    public static string? GetFileName(int resourceId) => fileById.TryGetValue(resourceId, out var f) ? f : null;

    public static IReadOnlyDictionary<int, string> Files => fileById;
}
